src/ProChat/container/index.tsx, src/ProChat/demos/meta.tsx, src/ProChat/mocks/threebody.ts, src/ProChat/store/action.ts, src/ProChat/store/initialState.ts, src/ProChat/types/config.ts, src/components/Avatar/index.tsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> feat: support onResetMessage funtion

src/ChatList/Item.tsx, src/ProChat/components/ChatList/Extras/Assistant.tsx, src/ProChat/components/ChatList/Extras/User.tsx, src/ProChat/components/InputArea/AutoCompleteTextArea.tsx, src/ProChat/components/InputArea/index.tsx, src/ProChat/container/index.tsx, src/ProChat/demos/default.tsx, src/ProChat/store/initialState.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> feat: support autocompleteRequest and messageItemExtraRender

src/ProChat/components/InputArea/AutoCompleteTextArea.tsx, src/ProChat/demos/default.tsx, src/ProChat/store/selectors/chat.ts, src/ProChat/types/config.ts, src/ProChat/types/meta.ts
=> feat:  usemeta support extra

src/ProChat/container/Provider.tsx, src/ProChat/container/index.tsx, src/ProChat/hooks/useProChat.ts, src/ProChat/store/initialState.ts, src/ProChat/store/store.ts, src/types/message.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> feat: support setMessageItem

src/ProChat/components/ChatList/Extras/Assistant.tsx, src/ProChat/components/ChatList/Extras/User.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> 🐛 fix: fix messageItemExtraRender item no set extra error

src/ProChat/utils/fetch.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
TextDecoder在将Uint8Array转为字符串的过程中，由于read()方法每次获取的是字节，当数据流中存在中文等多字节字符时，会出现将一个字符分成两次读取的情况，这时候decode会将不完全的字节尝试转字符串，会出现乱码。
---
参考[TextDecoder API文档示例](https://encoding.spec.whatwg.org/#example-end-of-stream)，如下，可以传递`stream: true`参数让decode在解码时关联整条流进行解码。
```js
var string = "", decoder = new TextDecoder(encoding), buffer;
while(buffer = next_chunk()) {
string += decoder.decode(buffer, {stream:true});
}
string += decoder.decode(); // end-of-queue
```
并且在最后一个chunk将stream参数设为false，结束流模式，处理最后的数据。修改后代码像这样：
```
while (!done) {
const { value, done: doneReading } = await reader.read();
done = doneReading;
const chunkValue = decoder.decode(value, { stream: !doneReading });
options.onMessageHandle?.(chunkValue, returnRes);
}
```
=> :bug: fix: TextDecoder多字节字符断开问题

src/ProChat/components/ScrollAnchor/index.tsx, src/ProChat/store/selectors/chat.ts, src/ProChat/store/selectors/index.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
比较特殊的场景，在 Steam 流式场景下，个人感觉是一次渲染的东西有点多，直接跳过了 useAtBottom 的判定从而不导致自动滚动了。
放开些严格的判定，1/3 屏幕（移动端），200 （PC）这样子的偏移感觉比较合理
=> :sparkles: fix: 修复特殊情况下滚动失效

src/BackBottom/index.tsx, src/ChatItem/style.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 修复回到最下方按钮丢失的问题

src/ProChat/store/action.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
After integrating the SidePanel environment into our browser plugin, we encountered a Content Security Policy (CSP) violation triggered by sending messages. Upon investigation, it was found that the issue stemmed from the use of the lodash template method. This problem occurred regardless of whether the inputTemplate was used or not, preventing message sending.
To resolve this, we modified the implementation to only use the template method when inputTemplate is utilized, which successfully fixed the error.
* https://developer.chrome.com/docs/extensions/reference/manifest/content-security-policy
* https://lodash.com/docs/4.17.15#template
For a more comprehensive solution to this issue in the future, an Ahead-of-Time …
=> fix: chrome extension csp error

docs/guide/demos/renderInputArea.tsx, docs/guide/multimodal.md, src/ProChat/components/InputArea/index.tsx, src/ProChat/container/App.tsx, src/ProChat/container/index.tsx, src/ProChat/demos/renderInputArea.tsx, src/ProChat/index.md
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: 支持自定义 InputArea 区域，并添加 多模态示范案例

docs/guide/demos/styles-chatitem.tsx, docs/guide/demos/styles-className.tsx, docs/guide/demos/styles-darkmode.tsx, docs/guide/demos/styles-inputarea.tsx, docs/guide/docs.md, docs/guide/servers-push.md, docs/guide/styles.md, src/ProChat/components/InputArea/AutoCompleteTextArea.tsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: feat: 添加自定义样式的指导文档

src/ChatItem/components/MessageContent.tsx, src/ChatItem/index.tsx, src/ChatItem/style.ts
- \[ ] ✨ feat
- \[x] 🐛 fix messageExtra类名不带有prefixClass
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
给messageExtra添加prefixClass，messageContent添加一个类名
无
=> messageExtra prefixClass类名缺失

src/ProChat/hooks/useProChat.ts, src/ProChat/store/action.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: useChat add getChatLoadingId

package.json, pnpm-lock.yaml, src/ChatItem/components/MessageContent.tsx, src/ChatItem/index.tsx, src/ChatItem/type.ts, src/ChatList/ChatListItem.tsx, src/ChatList/index.tsx, src/EditableMessage/index.tsx, src/MessageModal/index.tsx, src/ProChat/components/ChatList/index.tsx, src/ProChat/container/App.tsx, src/ProChat/container/index.tsx, src/ProChat/store/store.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
透传ProEditor的Markdown的两个markdown插件参数到ProChat来支持markdown插件
=> markdown支持插件

src/EditableMessage/index.tsx, src/MessageModal/index.tsx, src/ProChat/demos/doc-mode.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: slove markdown style null render problem

src/BackBottom/index.tsx, src/ProChat/container/App.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 修复有些时候回到底部按钮不展示的问题

src/ActionIconGroup/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
需求: 不传入dropdownMenu的时候, 则不展示...省略号
可以传入null来解决, 但是会被typescript校验不通过, 因此还是需要调整源码来修复此问题
=> 🐛 fix: ActionIconGroup不设置dropdownMenu, 依旧显示...省略号

src/ProChat/hooks/useProChat.ts, src/ProChat/store/reducers/message.ts
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
给pushChat扩展额外的参数
```
chatRef.current.pushChat({
content: 'Doding!',
id: 'opDqGn0G',
role: 'function',
createAt: 1234123,
});
```
close #209
=> :sparkles: feat: optimize pushChat function

demos/chatgpt-nextjs/package.json, demos/chatgpt-nextjs/src/app/api/openai/route.ts, docs/guide/chatgpt.en-US.md, docs/guide/chatgpt.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: update ai use docs

src/ProChat/store/selectors/chat.ts
userMeta 设置 backgroundColor 无效, 修改后支持从userMeta 获取 backgroundColor 的值来渲染
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> fix: userMeta设置backgroundColor 不生效的问题

src/ChatItem/components/Avatar.tsx, src/ProChat/demos/customeClassName.tsx, src/ProChat/index.en-US.md, src/ProChat/index.md, src/ProChat/mocks/customeClassName.ts, src/ProChat/store/selectors/chat.ts, src/ProChat/types/meta.ts, src/components/Avatar/index.tsx, src/types/meta.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
close #278
=> :sparkles: feat: assistantMeta 和 userMeta支持自定义类名

src/components/ChatList/index.tsx, src/components/ProChat/index.tsx, src/hooks/useChatList.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
chatList更新后滑动到底部
使用 `setTimeout` 确保滚动操作在 DOM 更新完成后执行
=> ⚡️ fix: chatList更新后滑动到底部

.github/workflows/preview.yml, .github/workflows/test.yml, package.json, src/ProChat/__test__/__snapshots__/demo.test.tsx.snap
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
1. 项目中应该配置一个 `packageManager`,  否则pnpm i 的时候容易出现以下错误
2. 快照更新
#302 这边demo 修改了需要更新快照。
#311 还有一个这边国际化的快照应该也需要更新以下。
=> 🔨  chore: add packageManager & update snap

src/hooks/useChatList.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
使用useMemo优化sendMessage中的消息生成
=> 使用useMemo优化sendMessage中的消息生成

src/components/ProChat/index.tsx, src/components/ProChatInputArea/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> feat: 添加setInputArea接口
