ant-design/pro-chat

src/ProChat/components/InputArea/ActionBar.tsx, src/ProChat/container/index.tsx, src/ProChat/demos/default.tsx, src/ProChat/demos/meta.tsx, src/ProChat/mocks/threebody.ts, src/ProChat/store/action.ts, src/ProChat/store/initialState.ts, src/ProChat/types/config.ts, src/components/Avatar/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> Add on reset message

src/ProChat/components/InputArea/AutoCompleteTextArea.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> fix: fix send auto clear no work error

.prettierrc.js, README.md, src/ChatItem/style.ts, src/ProChat/components/InputArea/ActionBar.tsx, src/ProChat/demos/request.tsx, src/ProChat/index.md, src/ProChat/store/initialState.ts, src/TokenTag/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> ✨ feat: 支持 actions  的自定义

src/ActionIcon/index.tsx, src/ActionIcon/style.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: fixed actionicon hover double mask

src/ProChat/components/InputArea/index.tsx, src/ProChat/store/initialState.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> ✨ feat: support inputAreaProps

src/ChatList/Item.tsx, src/ProChat/index.md, src/ProChat/store/action.ts, src/ProChat/store/initialState.ts, src/ProChat/utils/fetch.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> feat: support genMessageId

.gitignore, src/ActionIconGroup/index.tsx, src/ChatList/ActionsBar.tsx, src/ChatList/Item.tsx, src/ProChat/components/ChatList/Actions/index.ts, src/ProChat/components/ChatList/Messages/Hello.tsx, src/ProChat/components/ChatList/Messages/index.ts, src/ProChat/demos/helloMessage.tsx, src/ProChat/index.md, src/ProChat/store/initialState.ts, src/ProChat/store/selectors/chat.ts, src/ProChat/types/chat.ts, src/types/message.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: chatList hello dom support ReactNode

README.md, src/EditableMessage/index.tsx
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: ReadMe 更新

package.json, src/ProChat/components/ChatList/Actions/Assistant.tsx, src/ProChat/demos/sse.tsx, src/ProChat/index.md, src/ProChat/mocks/sseResponse.ts
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: add sse demo

LICENSE
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> ✨ feat: 1.0

package.json
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=>  🐛 fix: fix release

CHANGELOG.md, README.md, README.zh-CN.md, docs/guide/intro.md, src/ProChat/index.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
preview: https://github.com/ant-design/pro-chat/tree/docs/readme
=> 📝 docs: Perfect README

src/ProChat/container/App.tsx
links：https://github.com/ant-design/pro-chat/issues/23
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :zap: feat: change 100vw to 100%

docs/guide/error.md, docs/guide/sse.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: 添加 SSE 文档

.dumirc.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 修复首页快速开始路由跳转

.dumirc.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> 🐛 fix: intro page not found with en

README.md, demos/qwen-nextjs/src/app/globals.css, src/BackBottom/index.tsx, src/BackBottom/style.ts, src/ChatItem/index.tsx, src/ChatItem/type.ts, src/ChatList/ChatListItem.tsx, src/ChatList/index.tsx, src/ProChat/components/ChatList/index.tsx, src/ProChat/container/App.tsx, src/ProChat/container/index.tsx, src/ProChat/demos/bigData.tsx, src/ProChat/demos/request.tsx, src/ProChat/demos/use-ref.tsx, src/ProChat/index.md, src/ProChat/store/store.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> ✨ feat: support chatItemRenderConfig

src/ChatItem/index.tsx, src/ChatList/Item.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: slove avatar meta was not work

src/ChatItem/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: stream was done but loading icon is show

demos/chatgpt-nextjs/src/app/chatgpt/index.tsx, demos/qwen-nextjs/src/app/page.tsx, docs/guide/chatgpt.md, docs/guide/qwen.md
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> 🐛 fix: 修复next版本下首页渲染报错

src/ChatItem/index.tsx, src/ChatList/ChatListItem.tsx
fix：https://github.com/ant-design/pro-chat/issues/49
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix(memo): Slove Editable Button was not work

package.json
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: 清理无用依赖

README.md, README.zh-CN.md, demos/chatgpt-nextjs/next.config.js, demos/qwen-nextjs/next.config.js, docs/guide/intro-start.md, docs/guide/qwen.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: update NextJs config

docs/guide/docs.md, docs/guide/initial.md, docs/guide/nextjs.md, docs/guide/storage.md, docs/guide/umi.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: 更新一些使用案例的文档

src/BackBottom/index.tsx, src/ProChat/container/App.tsx, src/ProChat/container/index.tsx, src/ProChat/demos/backtoBottomConfig.tsx, src/ProChat/demos/doc-mode.tsx, src/ProChat/demos/draggable.tsx, src/ProChat/index.md
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: 添加 BackToBottom 按钮的各种配置透出

src/ChatItem/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: slove chatItemRenderConfig render not work use Default dom

src/ProChat/demos/meta.tsx, src/ProChat/demos/use-pro-chat.tsx, src/ProChat/store/reducers/message.test.ts, src/ProChat/store/reducers/message.ts, src/ProChat/store/selectors/chat.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 修复因为 Delete 导致的一些问题

demos/chatgpt-nextjs/src/app/api/openai/route.ts, docs/guide/chatgpt.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: 更新ChatGPT 的错误demo示例

src/ProChat/components/InputArea/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: slove button loading not work

docs/guide/chatItemRenderConfig.md, docs/guide/demos/controled-servers-push.tsx, docs/guide/servers-push.md
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: 更新服务端手动Push消息的案例

src/ProChat/components/InputArea/AutoCompleteTextArea.tsx, src/ProChat/demos/default.tsx, src/ProChat/store/initialState.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: support autoCompleteProps

package.json
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
=> :bookmark: chore: publish 1.10.0

src/ProChat/components/ScrollAnchor/index.tsx, src/ProChat/store/action.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :pencil2: fix: slove if return null, still loading flag problem

package.json, src/ProChat/store/action.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: slove sse output loading problem

src/ProChat/container/Provider.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
修改部分场景下ProChatProvider中对StoreUpdater的重复引入
=> 🔖 feat: 修改部分场景下ProChatProvider中对StoreUpdater的重复引入

package.json, src/ProChat/demos/doc-mode.tsx, src/ProChat/store/action.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: slove loading was not stop

src/ProChat/components/InputArea/index.tsx, src/ProChat/container/App.tsx, src/ProChat/container/index.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> feat: support sendButtonRender props

src/ProChat/__test__/index.test.tsx, src/ProChat/components/ChatList/index.tsx, src/locale/en-US.ts, src/locale/index.ts, src/locale/zh-CN.ts, src/types/locale.ts
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> chore: add new locale

package.json
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
=> :bookmark: feat: update version 1.12.0

src/ProChat/components/InputArea/index.tsx
link: https://github.com/ant-design/pro-chat/issues/134
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: slove send button not work

package.json
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: publish 1.12.1

src/ProChat/__test__/__snapshots__/demo.test.tsx.snap, src/ProChat/components/ChatList/index.tsx, src/ProChat/components/InputArea/ActionBar.tsx, src/ProChat/components/InputArea/index.tsx, src/ProChat/container/App.tsx, src/ProChat/container/Provider.tsx, src/ProChat/container/StoreUpdater.tsx, src/ProChat/demos/i18n.tsx, src/ProChat/hooks/useProChatLocale.ts, src/ProChat/index.en-US.md, src/ProChat/index.md, src/ProChat/index.tsx, src/ProChat/store/selectors/chat.ts, src/locale/index.ts
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
使用hook的方式引入国际化：
const { localeObject } = useProChatLocale();
在主页添加了国际化的例子
对于无法使用hook的情况下，还是使用gLocaleObject(locale)的方式来做
=> :globe_with_meridians: chore: update i18n hook

docs/guide/chatItemRenderConfig.en-US.md, docs/guide/chatItemRenderConfig.md, docs/guide/demos/antd-configprovider.tsx, docs/guide/demos/render-chats-nextGen.tsx, docs/guide/demos/render-form-chats.tsx, src/ProChat/store/selectors/chat.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :memo: docs: add deep render docs

src/ProChat/__test__/__snapshots__/demo.test.tsx.snap, src/ProChat/__test__/index.test.tsx, src/ProChat/demos/control.tsx, src/ProChat/mocks/basic.ts, src/ProChat/store/selectors/chat.ts, tests/demo.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 解决受控情况下，有些 Chats 数据依然不被受控的问题

src/ProChat/demos/sse-trans.tsx, src/ProChat/hooks/useProChat.ts, src/ProChat/index.md, src/ProChat/store/action.ts, src/ProChat/store/initialState.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> 「WIP」:sparkles: feat: 添加 transformToChatMessage 的转换并添加 pushChat hooks

docs/guide/demos/error-custom.tsx, docs/guide/demos/error.tsx, docs/guide/demos/mocks/streamResponse.ts, src/ChatItem/components/ErrorContent.tsx, src/ChatItem/index.tsx, src/ChatItem/type.ts, src/ChatList/ChatListItem.tsx, src/ProChat/components/ChatList/index.tsx, src/ProChat/container/App.tsx, src/ProChat/container/index.tsx, src/ProChat/demos/doc-mode.tsx, src/ProChat/demos/error.tsx, src/ProChat/index.md, src/ProChat/mocks/streamResponse.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
=> :sparkles: feat: 支持自定义 Error 渲染 & 配套文档

package.json
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
=> :bookmark: feat: 发布版本 v1.13.0

src/ProChat/container/Provider.tsx, src/ProChat/container/StoreUpdater.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: inputAreaProps 变化的时候应该重新触发渲染

src/ProChat/components/ChatList/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 解决 Local 有些时候无效的问题

src/ProChat/__test__/__snapshots__/demo.test.tsx.snap, src/ProChat/container/OverrideStyle/global.ts
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 全局 CSS 影响问题去除

package.json
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
=> :bookmark: feat: version publish

src/ProChat/components/InputArea/index.tsx, src/ProChat/demos/request.tsx, src/ProChat/store/initialState.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: support input area value controlled

src/ProChat/__test__/__snapshots__/demo.test.tsx.snap, src/ProChat/components/InputArea/ActionBar.tsx, src/ProChat/demos/i18n.tsx, src/locale/index.ts, src/locale/zh-HK.ts
添加了繁体中文
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> feat: 新增繁体中文

src/ProChat/container/Provider.tsx, src/ProChat/container/StoreUpdater.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 解决一些特殊无法渲染更新的问题

src/BackBottom/index.tsx, src/ProChat/container/App.tsx, src/ProChat/container/index.tsx, src/ProChat/demos/bigData.tsx, src/ProChat/index.en-US.md, src/ProChat/index.md
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: add onScroll listener

src/ProChat/components/InputArea/index.tsx, src/ProChat/demos/request.tsx
…t work
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix:  修复输入框受控模式下中文无法输入的问题

docs/guide/umi.en-US.md, docs/guide/umi.md
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
fix the docs error
=> 🐛 fix:  docs error

docs/guide/demos/mocks/streamResponse.ts, src/ProChat/mocks/streamResponse.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
模拟对话返回信息的时候, 如果存在emoji表情, 会进行拆分, 导致变成无法识别的乱码
=> 🐛 fix: 解决MockResponse下, emoji乱码问题

docs/guide/whyUseProChat.en-US.md, docs/guide/whyUseProChat.md, package.json, src/ProChat/components/InputArea/AutoCompleteTextArea.tsx, src/ProChat/store/initialState.ts
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> fix: 修复 input text ref 透传失败的问题

src/ProChat/__test__/__snapshots__/demo.test.tsx.snap, src/ProChat/container/OverrideStyle/global.ts, src/ProChat/container/OverrideStyle/index.ts
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[x] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
避免使用影响过大的全局样式。
close #228
=> :lipstick: style: 将所有全局样式收敛至 .ant-pro-chat 内

package.json
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
=> :bookmark: feat: 新版本发布

src/ActionIconGroup/index.tsx, src/ChatItem/type.ts, src/ChatList/ActionsBar.tsx, src/ChatList/ChatListItem.tsx, src/ProChat/__test__/__snapshots__/demo.test.tsx.snap, src/ProChat/__test__/index.test.tsx, src/ProChat/components/ChatList/Actions/Assistant.tsx, src/ProChat/components/ChatList/Actions/Error.tsx, src/ProChat/components/ChatList/Actions/Fallback.tsx, src/ProChat/components/ChatList/Actions/Function.tsx, src/ProChat/components/ChatList/Actions/User.tsx, src/ProChat/components/ChatList/index.tsx, src/ProChat/demos/callbacks.tsx, src/ProChat/hooks/useProChat.ts, src/ProChat/index.en-US.md, src/ProChat/index.md, src/hooks/useChatListActionsBar.tsx, src/hooks/useCustomChatListAction.tsx
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
添加编辑的回调函数
close #205
=> feat: add callbacks

package.json, src/ProChat/__test__/index.test.tsx, src/ProChat/container/App.tsx, src/ProChat/store/reducers/message.test.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :bug: fix: 修复窗口特殊情况下不停 Shaking 的问题

package.json, pnpm-lock.yaml, src/ProChat/__test__/__snapshots__/demo.test.tsx.snap, src/ProChat/container/App.tsx, src/ProChat/demos/doc-mode.tsx, src/ProChat/demos/listener.tsx, src/ProChat/index.en-US.md, src/ProChat/index.md, src/ProChat/store/action.ts, src/ProChat/store/initialState.ts, src/ProChat/utils/fetch.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: 增加 chats 的三个回掉

src/ProChat/mocks/streamResponse.ts, src/ProChat/store/action.ts, src/ProChat/store/initialState.ts, src/ProChat/store/reducers/message.ts, src/ProChat/utils/fetch.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> feat: 更新 Request 支持更多自定义设置

package.json
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[x] 🔨 chore
- \[ ] 📝 docs
=> :bookmark: feat: release version 1.15.0

package.json, src/ProChat/mocks/streamResponse.ts, src/ProChat/store/action.ts, src/ProChat/store/reducers/message.ts
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> fix: delete console log

src/ProChat/container/App.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
close #183
=> 🐛 fix: 清空对话后，【返回底部】按钮未隐藏

src/ActionIcon/style.ts, src/BackBottom/style.ts, src/ProChat/container/App.tsx
- \[ x] 🐛 fix
useStyles 在 Model 或者 Drawer 中会有为空的情况。
=> fix: 修复 useStyles 可能引发的异常

src/ProChat/components/InputArea/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
当处于 Loading 状态时，禁用没有按下 Shift 键的 Enter
close #283
=> :bug: fix: disable Enter when loading

docs/guide/sse.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
- 更新文档 typo
- 增加 ai 包链接信息
=> 📝 docs: update ai use docs

src/ChatItem/demos/index.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
修复 ChatItem 文档中的展示异常问题
Before:
After:
=> 🐛 fix: ChatItem demo error

src/ProChat/container/App.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
close #279
=> 🐛 fix: 在antd对话框中使用，消息输入太多撑开输入框，然后就缩不回去了

src/ProChat/store/selectors/chat.ts
This reverts commit 4a0b82051804a6fad2b0da10bcc9bce3ede51933.
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> Revert "fix: userMeta设置backgroundColor 不生效的问题 (#295)"

package.json, src/ProChat/__test__/__snapshots__/demo.test.tsx.snap, src/ProChat/__test__/index.test.tsx, src/ProChat/demos/actions.tsx
- \[ ] ✨ feat
- \[x] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :pencil2: fix: ci update fixed

README.md, README.zh-CN.md, docs/guide/nextjs.en-US.md, docs/guide/nextjs.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[x] 📝 docs
文档中增加 Next.js 常见问题的处理
=> 📝 docs: add solutions for nextjs problems

src/ProChat/demos/i18n.tsx, src/locale/cs-CZ.ts, src/locale/de-DE.ts, src/locale/hu-HU.ts, src/locale/index.ts, src/locale/pl-PL.ts, src/locale/sk-SK.ts
- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
Added support for new languages: Czech (cz), German (de), Hungarian (hu), Polish (pl), and Slovak (sk).
This update includes translations for the following languages:
- Czech (cz)
- German (de)
- Hungarian (hu)
- Polish (pl)
- Slovak (sk)
These translations cover all the necessary UI elements and messages.
=> Add locales

package.json, src/ActionIconGroup/index.tsx, src/ChatItem/index.tsx, src/ChatItem/type.ts, src/ChatList/ChatListItem.tsx, src/ChatList/index.tsx, src/ProChat/demos/actions-chat-item.tsx, src/ProChat/index.en-US.md, src/ProChat/index.md
- \[ ] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs
=> :sparkles: feat: 新增加每个单元的自定义渲染按钮配置透出
